### ISSUE TITLE
Add explicit permissions to workflow examples

### ISSUE THREAD

**Issue by nepalevov** [epam/ai-dial-ci#229]
### Name and Version

all

### What is the problem this feature will solve?

- Codequality scan will stop rising "security" alerts, e.g. https://github.com/epam/ai-dial-sdk/security/code-scanning/12
- additional hardening(?)

If a GitHub Actions job or workflow has no explicit permissions set, then the repository permissions are used. Repositories created under organizations inherit the organization permissions. The organizations or repositories created before February 2023 have the default permissions set to read-write. Often these permissions do not adhere to the principle of least privilege and can be reduced to read-only, leaving the write permission only to a specific types as issues: write or pull-requests: write.

### What is the feature you are proposing to solve the problem?

1. Add the permissions key to the job or the root of workflow (in this case, it is applied to all jobs in the workflow that do not have their own permissions key) and assign the least privileges required to complete the task:

```
name: "My workflow"
permissions:
  contents: read
  pull-requests: write
```
or
```
jobs:
  my-job:
    permissions:
      contents: read
      pull-requests: write
```

2. For all repos, change the default token permission to `read` in repository settings

### What alternatives have you considered?

Permanentely disable codequality for github actions. For unknown reasons, seems it re-enables after workflow version update (?)
